using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Wapping_time
{
    public partial class AddMaterialPage : System.Web.UI.Page
    {
        private readonly string connString = ConfigurationManager.ConnectionStrings["ReadCardDB"].ConnectionString;
        protected int selectedLessonID
        {
            get { return ViewState["selectedLessonID"] != null ? (int)ViewState["selectedLessonID"] : 0; }
            set { ViewState["selectedLessonID"] = value; }
        }
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                selectedLessonID = int.Parse(Request.QueryString["LessonID"]);
            }
        }

        protected void btnSave_Click(object sender, EventArgs e)
        {
            // Grab the raw HTML string generated by TinyMCE
            string htmlContent = txtMaterialContent.Text;
            string materialName = materialLbl.Text;
            int lessonID = selectedLessonID;

            using (SqlConnection conn = new SqlConnection(connString))
            {
                conn.Open();

                // 1. Insert into Content Table and return the new ID
                string insertContentQuery = @"INSERT INTO Content (LessonID, Position, Type) 
                              VALUES (@LessonID, (SELECT ISNULL(MAX(Position), 0) + 1 FROM Content WHERE LessonID = @LessonID), 'Material');
                              SELECT SCOPE_IDENTITY();";

                int newContentID = 0;
                using (SqlCommand cmd = new SqlCommand(insertContentQuery, conn))
                {
                    cmd.Parameters.AddWithValue("@LessonID", lessonID);
                    newContentID = Convert.ToInt32(cmd.ExecuteScalar());
                }

                // 2. Insert the actual TinyMCE text into MaterialContent
                string insertMaterialQuery = @"INSERT INTO MaterialContent (ContentID, Name, Description, ImageName) 
                                       VALUES (@ContentID, @Name, @Description, @ImageName);";

                using (SqlCommand cmd = new SqlCommand(insertMaterialQuery, conn))
                {
                    cmd.Parameters.AddWithValue("@ContentID", newContentID);
                    cmd.Parameters.AddWithValue("@Name", materialName);
                    cmd.Parameters.AddWithValue("@Description", htmlContent); // Storing the HTML directly!
                    cmd.Parameters.AddWithValue("@ImageName", "materialName");

                    cmd.ExecuteNonQuery();
                }
            }

            // Redirect back to your main workspace page
            Response.Redirect("CoursePage.aspx");
        }
    }
}