using System;
using System.IO;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Wapping_time
{
    public partial class AddMaterialPage : System.Web.UI.Page
    {
        private readonly string connString = ConfigurationManager.ConnectionStrings["ReadCardDB"].ConnectionString;
        protected int selectedLessonID
        {
            get { return ViewState["selectedLessonID"] != null ? (int)ViewState["selectedLessonID"] : 0; }
            set { ViewState["selectedLessonID"] = value; }
        }
        protected int selectedMaterialID
        {
            get { return ViewState["selectedMaterialID"] != null ? (int)ViewState["selectedMaterialID"] : 0; }
            set { ViewState["selectedMaterialID"] = value; }
        }
        protected string selectedMode
        {
            get { return ViewState["selectedMode"] != null ? (string)ViewState["selectedMode"] : ""; }
            set { ViewState["selectedMode"] = value; }
        }
        protected int selectedFlashcardID
        {
            get { return ViewState["selectedFlashcardID"] != null ? (int)ViewState["selectedFlashcardID"] : 0; }
            set { ViewState["selectedFlashcardID"] = value; }
        }
        public string CurrentMode
        {
            get { return selectedMode; }
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            hdnUploadPath.Value = "Math Image/Material";
            if (!IsPostBack)
            {
                selectedMode = Request.QueryString["Mode"];

                if (selectedMode == "Edit")
                {
                    selectedMaterialID = int.Parse(Request.QueryString["MaterialID"]);
                    LoadMaterial(selectedMaterialID);
                    LoadFlashcards();
                }

                selectedLessonID = int.Parse(Request.QueryString["LessonID"]);
            }
            else
            {
                if (ViewState["CardEditMode"] != null && (bool)ViewState["CardEditMode"])
                {
                    btnEditCards.Visible = false;
                    btnDoneCards.Visible = true;
                    ScriptManager.RegisterStartupScript(this, this.GetType(), "cardEdit", "enableCardEdit();", true);
                }
            }
        }

        protected void btnSave_Click(object sender, EventArgs e)
        {
            if (selectedMode == "Add")
            {
                string materialName = materialLbl.Text;
                string htmlContent = txtMaterialContent.Text;   // Grab the raw HTML string generated by TinyMCE


                using (SqlConnection conn = new SqlConnection(connString))
                {
                    conn.Open();

                    // 1. Insert into Content Table and return the new ID
                    string insertContentQuery = @"INSERT INTO Content (LessonID, Position, Type) 
                                  VALUES (@LessonID, (SELECT ISNULL(MAX(Position), 0) + 1 FROM Content WHERE LessonID = @LessonID), 'Material');
                                  SELECT SCOPE_IDENTITY();";

                    int newContentID = 0;
                    using (SqlCommand cmd = new SqlCommand(insertContentQuery, conn))
                    {
                        cmd.Parameters.AddWithValue("@LessonID", selectedLessonID);
                        newContentID = Convert.ToInt32(cmd.ExecuteScalar());
                    }

                    // 2. Insert the actual TinyMCE text into MaterialContent
                    string insertMaterialQuery = @"INSERT INTO MaterialContent (ContentID, Name, Description) 
                                           VALUES (@ContentID, @Name, @Description);
                                           SELECT SCOPE_IDENTITY();";

                    using (SqlCommand cmd = new SqlCommand(insertMaterialQuery, conn))
                    {
                        cmd.Parameters.AddWithValue("@ContentID", newContentID);
                        cmd.Parameters.AddWithValue("@Name", materialName);
                        cmd.Parameters.AddWithValue("@Description", htmlContent); // Storing the HTML directly
                        selectedMaterialID = Convert.ToInt32(cmd.ExecuteScalar());
                    }
                }
                selectedMode = "Edit";
                ViewState["SelectedMode"] = "Edit";
            }
            else if (selectedMode == "Edit")
            {
                string updateString = @"UPDATE [MaterialContent] SET Name = @Name, Description = @Description WHERE MaterialID = @MaterialID";
                using (SqlConnection conn = new SqlConnection(connString))
                {
                    conn.Open();
                    using (SqlCommand cmd = new SqlCommand(updateString, conn))
                    {
                        string materialName = materialLbl.Text;
                        string htmlContent = txtMaterialContent.Text;

                        cmd.Parameters.AddWithValue("@Name", materialName);
                        cmd.Parameters.AddWithValue("@Description", htmlContent);
                        cmd.Parameters.AddWithValue("@MaterialID", selectedMaterialID);

                        cmd.ExecuteNonQuery();
                    }
                }
            }

            //Response.Redirect("AdminEditCoursePage.aspx?LessonID=" + selectedLessonID + "&type=material");

        }

        void LoadMaterial(int materialID)
        {
            if (selectedMaterialID == 0) return;
            string selectMaterial = @"SELECT Name, Description FROM [MaterialContent] WHERE MaterialID = @MaterialID;";

            using (SqlConnection conn = new SqlConnection(connString))
            {
                conn.Open();

                using (SqlCommand cmd = new SqlCommand(selectMaterial, conn))
                {
                    cmd.Parameters.AddWithValue("@MaterialID", materialID);

                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        reader.Read();
                        string materialName = reader["Name"].ToString();
                        string materialDescription = reader["Description"].ToString();

                        materialLbl.Text = materialName;
                        txtMaterialContent.Text = materialDescription;
                    }
                }
            }
        }

        private void LoadFlashcards()
        {
            using (SqlConnection conn = new SqlConnection(connString))
            {
                conn.Open();
                string query = "SELECT FlashcardID, FrontImage, BackText FROM Flashcard WHERE MaterialID = @MaterialID ORDER BY CardOrder";
                SqlDataAdapter adapter = new SqlDataAdapter(query, conn);
                adapter.SelectCommand.Parameters.AddWithValue("@MaterialID", selectedMaterialID);
                DataTable table = new DataTable();
                adapter.Fill(table);
                FlashcardRepeater.DataSource = table;
                FlashcardRepeater.DataBind();
            }
        }

        protected void saveCards()
        {
            string backText = cardBackText.Text;
            string imageName = "";

            if (checkValidPath(ref imageName))
            {
                using (SqlConnection conn = new SqlConnection(connString))
                {
                    conn.Open();
                    string query = "INSERT INTO Flashcard (MaterialID, FrontImage, BackText, CardOrder) VALUES (@MaterialID, @FrontImage, @BackText, (SELECT ISNULL(MAX(CardOrder), 0) + 1 FROM Flashcard WHERE MaterialID = @MaterialID))";
                    SqlCommand cmd = new SqlCommand(query, conn);
                    cmd.Parameters.AddWithValue("@MaterialID", selectedMaterialID);
                    cmd.Parameters.AddWithValue("@FrontImage", imageName);
                    cmd.Parameters.AddWithValue("@BackText", backText);
                    cmd.ExecuteNonQuery();
                }
            }
        }

        protected bool checkValidPath(ref string imageName)
        {
            if (cardImageUpload.HasFile)
            {
                imageName = "img_" + Guid.NewGuid().ToString().Substring(0, 8) + System.IO.Path.GetExtension(cardImageUpload.FileName);
                string subFolder = hdnUploadPath.Value;

                string directoryPath;
                string relativeUrlPath;

                // Check if a specific subfolder layout (like "Math Image/Material") was given
                if (!string.IsNullOrEmpty(subFolder))
                {
                    // If yes, append the subfolder paths cleanly
                    directoryPath = Server.MapPath("~/Images/" + subFolder + "/");
                    relativeUrlPath = "/Images/" + subFolder + "/" + imageName;
                }
                else
                {
                    // If empty, save to the "Images" directory
                    directoryPath = Server.MapPath("~/Images/");
                    relativeUrlPath = "/Images/" + imageName;
                }

                cardImageUpload.SaveAs(System.IO.Path.Combine(directoryPath, imageName));

                imageName = relativeUrlPath;
                return true;
            }
            return false;
        }

        protected void btnAddCard_Click(object sender, EventArgs e)
        {
            if (selectedFlashcardID > 0)
            {
                // Update existing card
                string imageName = "";
                if(checkValidPath(ref imageName))
                {
                    using (SqlConnection conn = new SqlConnection(connString))
                    {
                        conn.Open();

                        // Get image path
                        string getQuery = "SELECT FrontImage FROM FlashCard WHERE FlashcardID = @FlashcardID";
                        SqlCommand getCmd = new SqlCommand(getQuery, conn);
                        getCmd.Parameters.AddWithValue("@FlashcardID", selectedFlashcardID);
                        string imgFile = getCmd.ExecuteScalar().ToString();

                        string query = "UPDATE Flashcard SET BackText = @BackText, FrontImage = @FrontImage WHERE FlashcardID = @FlashcardID";
                        SqlCommand cmd = new SqlCommand(query, conn);
                        cmd.Parameters.AddWithValue("@BackText", cardBackText.Text);
                        cmd.Parameters.AddWithValue("@FrontImage", imageName);
                        cmd.Parameters.AddWithValue("@FlashcardID", selectedFlashcardID);
                        cmd.ExecuteNonQuery();

                        // image pathsand delete files
                        if (!string.IsNullOrEmpty(imgFile))
                        {
                            string fullPath = Server.MapPath(imgFile);
                            if (File.Exists(fullPath))
                            {
                                File.Delete(fullPath);
                            }
                        }

                    }
                }
                else
                {
                    using (SqlConnection conn = new SqlConnection(connString))
                    {
                        conn.Open();

                        string query = "UPDATE Flashcard SET BackText = @BackText WHERE FlashcardID = @FlashcardID";
                        SqlCommand cmd = new SqlCommand(query, conn);
                        cmd.Parameters.AddWithValue("@BackText", cardBackText.Text);
                        cmd.Parameters.AddWithValue("@FlashcardID", selectedFlashcardID);
                        cmd.ExecuteNonQuery();
                    }
                }
                selectedFlashcardID = 0;
                btnAddCard.Text = "Add Card";

            }
            else
            {
                if(System.IO.Path.GetExtension(cardImageUpload.FileName) != "" || cardBackText.Text != "")
                {
                    saveCards();
                }
            }
            cardBackText.Text = "";
            Response.Redirect($"MaterialPage.aspx?Mode=Edit&LessonID={selectedLessonID}&MaterialID={selectedMaterialID}");
            LoadFlashcards();
        }

        protected void btnEditCard_Click(object sender, EventArgs e)
        {
            ViewState["CardEditMode"] = true;
            btnEditCards.Visible = false;
            btnDoneCards.Visible = true;
            LoadFlashcards();
            ScriptManager.RegisterStartupScript(this, this.GetType(), "cardEdit", "enableCardEdit();", true);
        }

        protected void btnDoneCard_Click(object sender, EventArgs e)
        {
            ViewState["CardEditMode"] = false;
            btnEditCards.Visible = true;
            btnDoneCards.Visible = false;
            cardBackText.Text = "";
            LoadFlashcards();
            ScriptManager.RegisterStartupScript(this, this.GetType(), "cardDone", "disableCardEdit();", true);
        }

        protected void selectFlashCard(object source, RepeaterCommandEventArgs e)
        {
            int flashcardID = int.Parse(e.CommandArgument.ToString());

            if (e.CommandName == "DeleteCard")
            {
                using (SqlConnection conn = new SqlConnection(connString))
                {
                    conn.Open();
                    string query = "DELETE FROM Flashcard WHERE FlashcardID = @FlashcardID";
                    SqlCommand cmd = new SqlCommand(query, conn);
                    cmd.Parameters.AddWithValue("@FlashcardID", flashcardID);
                    cmd.ExecuteNonQuery();
                }
                LoadFlashcards();
            }
            else if (e.CommandName == "EditCard")
            {
                using (SqlConnection conn = new SqlConnection(connString))
                {
                    conn.Open();
                    string query = "SELECT BackText FROM Flashcard WHERE FlashcardID = @FlashcardID";
                    SqlCommand cmd = new SqlCommand(query, conn);
                    cmd.Parameters.AddWithValue("@FlashcardID", flashcardID);
                    cardBackText.Text = cmd.ExecuteScalar().ToString();
                    selectedFlashcardID = flashcardID;
                }
                btnAddCard.Text = "Update Card";
                ScriptManager.RegisterStartupScript(this, this.GetType(), "editCard", "highlightEditCard('" + flashcardID + "');", true);
            }
        }
    }
}